[package]
name = "sporec-codegen"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Spore execution and future backend experiments"
repository.workspace = true
license.workspace = true

[dependencies]
cranelift-codegen = { workspace = true }
cranelift-frontend = { workspace = true }
cranelift-jit = { workspace = true }
cranelift-module = { workspace = true }
cranelift-native = { workspace = true }
sporec-parser = { path = "../sporec-parser" }
sporec-stdlib = { path = "../sporec-stdlib" }
